### ISSUE TITLE
Trūksta Nemuno atkarpos

### ISSUE THREAD

**Issue by paumas** [openmaplt/vector-map#111]
Trūksta Nemuno atkarpos
https://openmap.lt/#m/12.45/55.08319/21.99046/0/0

**Comment by tomass** [comment]
_lithuania.poly_ failas apibrėžia per mažą poligoną, į kurį netelpa dingstanti Nemuno upės ploto geometrija, todėl šis objektas ir dingsta vykdant kai kuriuos duomenų atnaujinimus.

**Comment by tomass** [comment]
Duomenys perkrauti, poligonas atsirado.
_lithuani.poly_ PR'e.
