### ISSUE TITLE
Generalizuotų duomenų atnaujinimas

### ISSUE THREAD

**Issue by tomass** [openmaplt/vector-map#165]
Generalizacija daroma šeštadieniais.
Jei kaladėlės X duomenys pasikeitė ne penktadienį (t.y. ne prieš šeštadienio atnaujinimą), tai kaladėlė bus pergeneruota kitą dieną su senais generalizuotais duomenimis. Šeštadienį ji nebus pergeneruojama. Taigi turime daug kaladėlių su senais generalizuotais duomenimis, nesutampančiais duomenimis ir pan.

Todėl reikia:
1. Visomis dienomis išskyrus generalizacijos dieną (šeštadienį) purvinų kaladėlių sąrašo failą akumuliuoti (cat dirty_tiles >> acc_dirty_tiles).
2. Šeštadienį:
a) paskutinį kartą suakumuliuoti purvinų kaladėlių sąrašą,
b) iš akumuliuoto sąrašo pašalinti pasikartojančias eilutes,
c) vykdyti standartinę kaladėlių atnaujinimo procedūrą, tik su akumuliuotu purvinų kaladėlių sąrašu _acc_dirty_tiles_,
d) ištrinti akumuliuotų kaladėlių failą.

**Comment by ramunasd** [comment]
Paprasčiau būtų pergeneruoti visus aukštesnius lygius, kad ir kas naktį.

**Comment by tomass** [comment]
Norisi išbandyti procesą su skirtingais atnaujinimo dažniais (tarkim poi apskritai galima būtų atnaujinti kas valandą-dvi). Žinoma tam reikėtų sluoksnių hierarchiją pertvarkyti.
Generalizacijos tik daugės, kažkada atsiras labai sudėtingų operacijų ir per naktį gali nebespėti susukti.

Bet gal ir tiesą sakai, **kai** bus daug generalizacijos, **tada** bus galima ir padaryti sudėtingesnį variantą.

**Comment by tomass** [comment]
Kadangi sprendimas labai jau paprastas, visgi jį padariau dabar.
