### ISSUE TITLE
https://openmap.lt/glyphs/Roboto%20Italic/0-255.pbf not found

### ISSUE THREAD

**Issue by ramunasd** [openmaplt/vector-map#199]
ortofoto mišrus, zoom 8-14 visiškai nerodo kelių ir vietovių pavadinimų

**Comment by tomass** [comment]
Pataisiau _Roboto Italic_ -> _Roboto Condensed Italic_. Šitas šriftas buvo naudojamas tik vandens etiketėms, bet panašu jo neradus ir kiti elementai nukrenta.
Vietovių ir kelių pavadinimus matau:
![paveikslas](https://user-images.githubusercontent.com/969513/47072010-c6f9f080-d1fd-11e8-8b0e-f88e81aab93b.png)

**Comment by ramunasd** [comment]
ačiū
