### ISSUE TITLE
Miško polygoną blogai rodo

### ISSUE THREAD

**Issue by ramunasd** [openmaplt/vector-map#221]
![image](https://user-images.githubusercontent.com/150403/50990311-5facbd80-151a-11e9-9cee-5c3f1509488c.png)

**Comment by tomass** [comment]
Generalizuota geometrija gera ir validi, bet Tegola arba Mapboxgljs su ja šitame konkrečiame mastelyje nesusitvarko.
Bandysiu keisti generalizavimo parametrus.

**Comment by tomass** [comment]
Tegola vektorinę kaladėlę sugeneruoja gerai. Mapbox-gl-js nesugeba parodyti.

**Comment by tomass** [comment]
Vektorinės kaladėlės duomenys (iki pakeitimų), kuriuose mapbox-gl-js vaizdavo su problemomis (kaip pateikta iliustracijoje aukščiau)
![paveikslas](https://user-images.githubusercontent.com/969513/50996193-ed43d980-1529-11e9-828e-406ac971c425.png)

**Comment by tomass** [comment]
Pataisyta:
![paveikslas](https://user-images.githubusercontent.com/969513/51044304-778f4a80-15c9-11e9-9a3d-39dfa663affb.png)

**Comment by ramunasd** [comment]
ačiū!
