### ISSUE TITLE
Nemunas turi kažkokią neaiškią liniją

### ISSUE THREAD

**Issue by paumas** [openmaplt/vector-map#23]
https://openmap.lt/#14.59/54.9014/23.875

Pastebėjau kad Kaune santakoje yra kažkokios linijos.
Ta pati linija matosi ir prie Nemuno prieplaukos

**Comment by tomass** [comment]
Vandens poligonams yra uždėtas rėmelis, kad vanduo labiau išsiskirtų vizualiai.
Nurodytoje vietoje susikerta trys riverbank (upės ploto) poligonai: dvi Nemuno dalys ir viena Neries.
Greitas sprendimas yra vėl nuimti rėmelį, bet tada vanduo ne taip gražiai kitose vietose atrodo.
Taigi kol kas nežinau, kaip padaryti gražiai (potencialiai gal padės poligonų sujungimas db užklausose).

**Comment by paumas** [comment]
Nu va dabar lygtais upės bent jau susitvarkė nuo 14 lygio.
Liko tik viena bėda, tai čia https://openmap.lt/#15.68/54.9062/23.8642, bet čia bėda manau yra su skirtingais pavadinimais ir jis negali sujungti į vieną polygoną.

**Comment by tomass** [comment]
Dabartinė rėmelio spalva bus dar švelninama (artinama prie vandens), tai matysis mažiau.
Bet linija ant susikirtimo kaipo tokia liks kaip yra dabar.
