### ISSUE TITLE
Visų pastatų aukštis vienodas

### ISSUE THREAD

**Issue by sirex** [openmaplt/vector-map#24]
Kaip, suprantu, šiuo metu visų pastatų aukštis yra vienodas ir neatsižvelgiama į aukštų skaičių nurodytą OSM duomenų bazėje?

![pazymejimas_001](https://user-images.githubusercontent.com/297583/31214530-416e813c-a9b4-11e7-9100-70053d522bd8.png)

**Comment by tomass** [comment]
Faile _osm2pgsql_ yra pridėtas naujas laukas _building:levels_. Kai bus perkurta db*, bus pataisytos užklausos, kad būtų imamas tikslesnis pastatų aukštis.
Beje, sudėtingiems pastatams, tokiems kaip iliustracijoje parodytas PC Europa, Radison viešbutis, Vilniaus miesto savivaldybė, yra naudojamos building:part dalys. Dabartinėje realizacijoje šių dalių dar nebuvo galvota naudoti. Tai ateities planuose.
* - naujų laukų pridėjimas reiškia pilną db perimportavimą, tai „sunkus“ procesas, todėl nedaromas iš karto.

**Comment by sirex** [comment]
O kaip atnaujinami duomenys? Kaip suprantu openmap.lt žemėlapyje rodomi ne realaus laiko duomenys? T.y. duomenys importuojami iš osm duomenų bazės, kas kažkiek laiko?

**Comment by paumas** [comment]
Duomenys yra atnaujinami 1 kartą paroje, 1 valandą nakties.
Būtų galima padažninti atnaujinimą, bet atnaujinimo procedūrą reikalauja nemažai serverio resursų, tad buvo nuspręsta atnaujinti vieną kartą dienoje.

**Comment by tomass** [comment]
Pastatų aukščiui naudojama informacija iš žymų _height_ ir _building:levels_.
