### ISSUE TITLE
Trūksta tilestash.cfg

### ISSUE THREAD

**Issue by xor22h** [openmaplt/vector-map#289]
Docker-compose faile minimas tiles.cfg, bet jo repositorijoje nėra: https://github.com/openmaplt/vector-map/blob/92a5d87ec1742c041c4d627dfb5d8b148113ca2b/docker-compose.yml#L11

`- "./tiles.cfg:/etc/tilestache/tilestache.cfg"`

**Comment by tomass** [comment]
Tilestache buvo naudojamas iki Tegolos, dabar jo nebereikia, tai ir jo konfigas neberikalintas.
Apskritai iš tilestache nieko nebereikia, nes nieko repozitorijoje jau ir nebėra.

**Comment by xor22h** [comment]
tai reiktu is docker-compose isimti tilestash, ir ideti tegola;

https://github.com/openmaplt/vector-map/issues/290
