### ISSUE TITLE
Hibridiniame žemėlapyje LV piktogramos neaktyvios

### ISSUE THREAD

**Issue by tomass** [openmaplt/vector-map#30]
Hibridiniame žemėlapyje paspaudus ant LV piktogramų turėtų vykti tas pats, kas vyksta paspaudus ant LV pagrindiniame žemėlapyje.

**Comment by paumas** [comment]
Šita bėda yra todėl, kad aš esu pririšęs tuos popup prie layer kurio id=label-amenity. Kiek žiūrėjau hibridiniame styliuje šis sluoksnis yra pavadintas poi. Tai yra keli sprendimo būdai:
1) suvienodinti lygių pavadinimus ir hybrid.json faile pervadinti poi į label-amenity.
2) suvienodinti lygių pavadinimus ir map.json faile pervadinti label-amenity į poi ir pataisyti map.js faile kodą.
3) papildyti map.js faile, kad popup interaktyvuną uždėtu tiek ant label-amenity, tiek ant poi sluoksnio.

Arba reikia sugalvoti kad interaktyvumą pririšti ne prie layer konkretaus, o pagal kažkokį kitą parametrą.
