### ISSUE TITLE
Papildoma informacija prie lankytinų vietų

### ISSUE THREAD

**Issue by tomass** [openmaplt/vector-map#45]
Lankytinų vietų kaladėlėse (poi sluoksnis) jau yra papildomi atributai, kuriuos reikėtų rodyti paspaudus ant lankytinos vietos. Žemiau pateikta tvarka, kuria šie atributai turėtų būti rodomi. Skliausteliuose dabar jau rodomi laukai:
* (name)
* official_name (Oficialus pavadinimas)
* alt_name (Kiti pavadinimai)
* city
* street
* housenumber (city, street ir housenumber rodomi vienoje eilutėje atskirti tarpais, „Adresas“)
* email (E-paštas)
* phone (Telefono nr.)
* (website)
* heritage (rodomas nuorodos tekstas „Kultūros vertybių registras“, url=https://kvr.kpd.lt/heritage/Pages/KVRDetail.aspx?lang=lt&MC=<heritage>
* wikipedia (nuoroda į lietuvišką wikipedia, t.y. nutriname priekyje :lt ir url formuojamas: lt.wikipedia.org/wiki/<page_title>, jei išeina, tarpus pakeičiame į „_“)
* height (aukštis)
* fee (Mokestis)

**Comment by paumas** [comment]
Sutvarkyta
