### ISSUE TITLE
Pergeneruoti coastline duomenis

### ISSUE THREAD

**Issue by tomass** [openmaplt/vector-map#83]
Šiuo metu prie Rusnės tilto išlenda iš apačios senas _coastline_ shape failas.

**Comment by ramunasd** [comment]
Gal paprasčiau būtų pridėti skriptą, kad iš http://openstreetmapdata.com/data/coastlines atnaujintų? Kažkokį variantą turėjau, galiu pasidalinti.

**Comment by tomass** [comment]
Jei yra kažkas automatinio - žinoma reikia naudoti! Laukiam skripto.

**Comment by ramunasd** [comment]
```
wget -q http://data.openstreetmapdata.com/water-polygons-split-3857.zip && \
unzip water-polygons-split-3857.zip && \
shp2pgsql -s 3857 -dDI water-polygons-split-3857/water_polygons.shp coastline | psql -U osm osm && \
rm -rf water-polygons-split-3857*
```

**Comment by paumas** [comment]
Gal ir gerai kad atnaujinai tą coastline, bet problemos su upės ir coastline sujungimą problemos neišsprendė.
https://openmap.lt/#m/15.82/55.33765/21.25341/0/0

**Comment by tomass** [comment]
Ir neturėjo išspręsti. Jungiami tik skirtingi vandens plotai iš OSM db, todėl tik tarp jų ir dingo rėmelio sukeliami efektai.
Coastline atnaujinimas išsprendė problemas aplink Rusnės salą, pvz. čia:
https://openmap.lt/#m/16.43/55.30102/21.38219/0/9
(anksčiau Rytinėje Rusnės tilto pusėje buvo likęs „baseinukas“, kuris ateidavo iš coastlines duomenų)
O pagrindinis coastline pasikeitimas yra tai, kad coastline buvo sumažinta iki Nemuno deltos (anksčiau coastline ėjo net ir aukščiau Nemunu virš Rusnės).
